import { useEffect, useState } from "react";
import { CheckCircle2, Printer, RefreshCw, TriangleAlert } from "lucide-react";
import { readPosPrinterSettings, savePosPrinterSettings, type PosPrinterSettings } from "@/lib/posPrinterSettings";
import { readLastNativeCheckoutStatus } from "@/lib/posNativeCheckoutBridge";
import { connectNativePrinter, disconnectNativePrinter, getNativePrinterStatus, listNativePrinters, nativeOpenCashDrawer, nativePrinterAvailable, nativeTestPrint, readSavedPrinterAddress, reconnectSavedPrinter, savePrinterAddress, type NativePrinterDevice } from "@/lib/thermalPrinter";

type PrinterStatus = { connected: boolean; name?: string; address?: string; connectionMethod?: string };

async function prepareReceiptLogo(file: File) {
  if (!file.type.startsWith("image/")) throw new Error("Choose a PNG, JPG or WebP logo image.");
  if (file.size > 5 * 1024 * 1024) throw new Error("Logo image must be smaller than 5 MB.");
  const source = URL.createObjectURL(file);
  try {
    const image = new Image();
    image.src = source;
    await new Promise<void>((resolve, reject) => {
      image.onload = () => resolve();
      image.onerror = () => reject(new Error("Could not read that logo image."));
    });
    const maxDimension = 600;
    const scale = Math.min(1, maxDimension / Math.max(image.naturalWidth, image.naturalHeight));
    const width = Math.max(1, Math.round(image.naturalWidth * scale));
    const height = Math.max(1, Math.round(image.naturalHeight * scale));
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    const context = canvas.getContext("2d");
    if (!context) throw new Error("Could not prepare the logo image.");
    context.drawImage(image, 0, 0, width, height);
    return canvas.toDataURL("image/png");
  } finally {
    URL.revokeObjectURL(source);
  }
}

export default function PrinterSettings() {
  const [settings,setSettings]=useState<PosPrinterSettings>(readPosPrinterSettings);
  const [saved,setSaved]=useState(false); const [testStatus,setTestStatus]=useState("");
  const [printers,setPrinters]=useState<NativePrinterDevice[]>([]); const [selectedAddress,setSelectedAddress]=useState(readSavedPrinterAddress());
  const [connected,setConnected]=useState(false); const [lastCheckout,setLastCheckout]=useState(readLastNativeCheckoutStatus); const native=nativePrinterAvailable();

  useEffect(()=>{if(!native)return;let cancelled=false;const restore=async()=>{const savedAddress=readSavedPrinterAddress();if(savedAddress&&!cancelled)setSelectedAddress(savedAddress);try{const devices=await listNativePrinters();if(!cancelled)setPrinters(devices);let status:PrinterStatus=await getNativePrinterStatus().catch(()=>({connected:false}));if(status.connected){const active=status.address||savedAddress;if(active){savePrinterAddress(active);if(!cancelled)setSelectedAddress(active);}if(!cancelled){setConnected(true);setTestStatus(`Connected${status.name?` to ${status.name}`:""}. Printer restored automatically.`);}return;}if(savedAddress){status=await reconnectSavedPrinter();if(!cancelled){setConnected(Boolean(status.connected));setTestStatus(status.connected?`Reconnected${status.name?` to ${status.name}`:" to saved printer"}.`:"Saved printer found but automatic reconnect failed. Tap Connect to retry.");}}else if(!cancelled)setTestStatus(devices.length?"Select the receipt printer, then Connect.":"No paired Bluetooth devices found. Pair the printer in Android settings first.");}catch(error){if(!cancelled)setTestStatus(error instanceof Error?error.message:"Could not restore Bluetooth printer");}};void restore();return()=>{cancelled=true};},[native]);
  useEffect(()=>{const update=()=>setLastCheckout(readLastNativeCheckoutStatus());window.addEventListener("customli:pos-native-checkout",update);return()=>window.removeEventListener("customli:pos-native-checkout",update);},[]);
  const update=<K extends keyof PosPrinterSettings>(key:K,value:PosPrinterSettings[K])=>{setSettings(current=>({...current,[key]:value}));setSaved(false);};
  const save=()=>{try{savePosPrinterSettings(settings);if(selectedAddress)savePrinterAddress(selectedAddress);setSaved(true);setTestStatus("Printer and receipt branding settings saved on this device.");}catch{setSaved(false);setTestStatus("Could not save settings. Try a smaller logo image.");}};
  const refreshPrinters=async()=>{setTestStatus("Reading paired Bluetooth devices…");try{const devices=await listNativePrinters();setPrinters(devices);const savedAddress=readSavedPrinterAddress();if(savedAddress)setSelectedAddress(savedAddress);setTestStatus(devices.length?"Paired devices refreshed.":"No paired Bluetooth devices found.");}catch(error){setTestStatus(error instanceof Error?error.message:"Could not read Bluetooth devices");}};
  const connect=async()=>{if(!selectedAddress)return setTestStatus("Select a Bluetooth printer first.");setTestStatus("Connecting directly to printer…");try{const result=await connectNativePrinter(selectedAddress);setConnected(result.connected);const device=printers.find(item=>item.address===selectedAddress);const printerName=result.name||device?.name||settings.printerName;const next={...settings,printerName};setSettings(next);savePosPrinterSettings(next);savePrinterAddress(selectedAddress);setSaved(true);setTestStatus(result.connected?`Connected to ${printerName}. Saved for checkout printing and cash drawer control.`:"Printer did not connect.");}catch(error){setConnected(false);setTestStatus(error instanceof Error?error.message:"Printer connection failed");}};
  const disconnect=async()=>{await disconnectNativePrinter().catch(()=>undefined);setConnected(false);setSelectedAddress("");setTestStatus("Printer disconnected and saved selection cleared.");};
  const ensureConnection=async()=>{let status:PrinterStatus=await getNativePrinterStatus().catch(()=>({connected:false}));if(!status.connected)status=await reconnectSavedPrinter();if(!status.connected)throw new Error("Saved printer could not reconnect. Tap Connect and try again.");setConnected(true);};
  const directTest=async()=>{save();if(!native)return setTestStatus("Install the Customli POS Android app for direct printer testing.");setTestStatus("Checking printer connection…");try{await ensureConnection();setTestStatus("Sending test receipt…");await nativeTestPrint();setTestStatus("Test receipt sent successfully.");}catch(error){setConnected(false);setTestStatus(error instanceof Error?error.message:"Native test failed");}};
  const drawerTest=async()=>{save();if(!native)return setTestStatus("Cash drawer testing requires the Customli POS Android app.");if(!settings.cashDrawerAttached)return setTestStatus("Turn on ‘Cash drawer connected to this printer’ first.");setTestStatus("Checking printer connection…");try{await ensureConnection();setTestStatus("Sending cash drawer open command…");await nativeOpenCashDrawer();setTestStatus("Cash drawer command sent. If the drawer did not open, check that its cable is connected to the printer cash-drawer port, then verify printer/drawer compatibility.");}catch(error){setConnected(false);setTestStatus(error instanceof Error?error.message:"Cash drawer test failed");}};
  const logoUpload=async(file?:File)=>{if(!file)return;setTestStatus("Preparing receipt logo…");try{const dataUrl=await prepareReceiptLogo(file);update("receiptLogoDataUrl",dataUrl);setTestStatus("Logo ready. Save settings, then print an order to verify the thermal result.");}catch(error){setTestStatus(error instanceof Error?error.message:"Could not prepare receipt logo");}};

  return <div className="mx-auto max-w-2xl space-y-5">
    <div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><Printer className="h-6 w-6"/>Printer & Receipt Setup</h1><p className="mt-1 text-sm text-slate-500">Set up this checkout device and receipt branding without technical configuration.</p></div>
    <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5">
      <div className={`rounded-xl border p-4 ${native?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><p className="text-sm font-black">{native?"Customli hardware connection ready":"Browser mode"}</p><p className="mt-1 text-xs text-slate-600">{native?"This device can control its Bluetooth receipt printer and attached cash drawer directly.":"Install the Customli POS Android app for direct printer and cash drawer control."}</p></div>
      {native&&<div className="space-y-3 rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-600">Receipt printer</p><p className={`text-sm font-bold ${connected?"text-emerald-700":"text-slate-500"}`}>{connected?"Connected":"Not connected"}</p></div><button type="button" onClick={refreshPrinters} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Scan paired</button></div><select value={selectedAddress} onChange={e=>{setSelectedAddress(e.target.value);setSaved(false)}} className="w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"><option value="">Select paired printer…</option>{printers.map(device=><option key={device.address} value={device.address}>{device.name} — {device.address}</option>)}</select><div className="grid grid-cols-2 gap-2"><button type="button" onClick={connect} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white">Connect & Save</button><button type="button" onClick={disconnect} className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-black">Disconnect</button></div></div>}
      <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Printer name</span><input value={settings.printerName} onChange={e=>update("printerName",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"/></label>
      <fieldset><legend className="text-xs font-bold uppercase tracking-wide text-slate-600">Paper width</legend><div className="mt-2 grid grid-cols-2 gap-3">{[58,80].map(width=><button key={width} type="button" onClick={()=>update("paperWidth",width as 58|80)} className={`rounded-xl border px-4 py-3 text-sm font-bold ${settings.paperWidth===width?"border-[#d7ae00] bg-[#fff6bf]":"border-slate-200 bg-white"}`}>{width} mm</button>)}</div></fieldset>

      <div className="space-y-4 rounded-xl border border-slate-200 p-4">
        <div><p className="text-sm font-black text-slate-900">Receipt branding</p><p className="mt-1 text-xs text-slate-500">These details make the POS reusable for any restaurant. The uploaded logo is converted automatically for monochrome thermal printing.</p></div>
        <div className="grid gap-4 sm:grid-cols-[120px_1fr] sm:items-start">
          <div className="flex h-28 items-center justify-center overflow-hidden rounded-xl border border-dashed border-slate-300 bg-slate-50 p-2">{settings.receiptLogoDataUrl?<img src={settings.receiptLogoDataUrl} alt="Receipt logo preview" className="max-h-full max-w-full object-contain"/>:<span className="px-2 text-center text-xs font-bold text-slate-400">NO LOGO</span>}</div>
          <div className="space-y-2"><label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Restaurant logo</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void logoUpload(e.target.files?.[0])} className="mt-2 block w-full text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-slate-900 file:px-3 file:py-2 file:font-bold file:text-white"/></label>{settings.receiptLogoDataUrl&&<button type="button" onClick={()=>update("receiptLogoDataUrl","")} className="text-xs font-bold text-red-600">Remove logo</button>}<p className="text-[11px] leading-4 text-slate-500">PNG, JPG or WebP. Dark-background logos are automatically inverted for thermal paper when needed.</p></div>
        </div>
        <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Restaurant name</span><input value={settings.receiptBusinessName} onChange={e=>update("receiptBusinessName",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"/></label>
        <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Location / receipt subtitle</span><input value={settings.receiptLocation} onChange={e=>update("receiptLocation",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"/></label>
        <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Website</span><input value={settings.receiptWebsite} onChange={e=>update("receiptWebsite",e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"/></label>
        <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-600">Membership QR destination</span><input value={settings.membershipQrUrl} onChange={e=>update("membershipQrUrl",e.target.value)} placeholder="https://..." className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3 text-sm"/><span className="mt-1 block text-[11px] text-slate-500">Leave blank to remove the membership QR from receipts.</span></label>
      </div>

      <label className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span><span className="block text-sm font-bold">Print automatically after payment</span><span className="block text-xs text-slate-500">Print the cashier and customer receipts after a successful sale.</span></span><input type="checkbox" checked={settings.autoPrint} onChange={e=>update("autoPrint",e.target.checked)} className="h-5 w-5"/></label>
      <div className="space-y-3 rounded-xl border border-slate-200 p-4"><label className="flex items-center justify-between"><span><span className="block text-sm font-bold">Cash drawer connected to this printer</span><span className="block text-xs text-slate-500">The drawer cable plugs into the receipt printer’s cash-drawer port.</span></span><input type="checkbox" checked={settings.cashDrawerAttached} onChange={e=>update("cashDrawerAttached",e.target.checked)} className="h-5 w-5"/></label>{settings.cashDrawerAttached&&<label className="flex items-center justify-between border-t border-slate-100 pt-3"><span><span className="block text-sm font-bold">Open automatically for cash payments</span><span className="block text-xs text-slate-500">Card, QR, Grab and other non-cash sales keep the drawer closed.</span></span><input type="checkbox" checked={settings.autoOpenCashDrawer} onChange={e=>update("autoOpenCashDrawer",e.target.checked)} className="h-5 w-5"/></label>}</div>
      <div className="grid gap-3 sm:grid-cols-3"><button type="button" onClick={save} className="rounded-xl bg-[#ffd400] px-4 py-3 text-sm font-black text-black">Save settings</button><button type="button" onClick={directTest} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white">Test Printer</button><button type="button" onClick={drawerTest} disabled={!settings.cashDrawerAttached} className="rounded-xl border border-slate-900 px-4 py-3 text-sm font-black disabled:cursor-not-allowed disabled:opacity-40">Test Cash Drawer</button></div>
      {saved&&<p className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Hardware and receipt branding settings saved on this device.</p>}{testStatus&&<p className="text-sm font-semibold text-slate-700">{testStatus}</p>}
      {lastCheckout&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-700"><p className="font-black text-slate-900">Last checkout hardware result · Ticket {lastCheckout.ticketNumber||"—"}</p><p>Receipt: <strong>{lastCheckout.printed?"SUCCESS":"NOT PRINTED"}</strong> — {lastCheckout.printMessage}</p><p>Cash drawer: <strong>{lastCheckout.drawerOpened?"OPEN COMMAND SENT":"NOT OPENED"}</strong> — {lastCheckout.drawerMessage||"No drawer result recorded"}</p><p>Order callout: <strong>{lastCheckout.callout?"SUCCESS":"NOT PLAYED"}</strong> — {lastCheckout.calloutMessage}</p><p className="text-slate-500">{new Date(lastCheckout.at).toLocaleString("en-GB",{hour12:false})}</p></div>}
    </section>
    {!native&&<section className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><TriangleAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-600"/><div className="text-xs leading-5 text-amber-900"><p className="font-bold">Hardware app required</p><p>Direct Bluetooth printing and cash drawer control are available in the Customli POS Android app.</p></div></section>}
  </div>;
}
