import { useEffect, useState } from "react";
import PosRegisterGate from "@/pages/PosRegisterGate";
import PosKitchen from "@/pages/PosKitchen";
import PosDisplay from "@/pages/PosDisplay";
import PosShifts from "@/pages/PosShifts";
import PrinterSettings from "@/pages/PrinterSettings";
import { DEVICE_ROLE_KEY, PRODUCT, type DeviceRole } from "@/config/product";
function navigate(path:string){window.history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"));}
function DeviceSetup(){const choose=(role:DeviceRole)=>{localStorage.setItem(DEVICE_ROLE_KEY,role);navigate(role==="register"?"/register":role==="kitchen"?"/kitchen":"/display");};return <main className="grid min-h-dvh place-items-center bg-zinc-950 p-6 text-white"><section className="w-full max-w-2xl rounded-3xl bg-white p-8 text-zinc-950 shadow-2xl"><p className="text-xs font-black uppercase tracking-[.25em] text-amber-500">{PRODUCT.owner}</p><h1 className="mt-2 text-4xl font-black">Set up this device</h1><p className="mt-3 text-zinc-600">Choose what this device does. You can change it later without reinstalling.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><button onClick={()=>choose("register")} className="rounded-2xl bg-amber-400 p-5 text-left font-black">POS Register<span className="mt-2 block text-sm font-medium">Take orders, payments and print tickets.</span></button><button onClick={()=>choose("kitchen")} className="rounded-2xl bg-zinc-900 p-5 text-left font-black text-white">Kitchen Display<span className="mt-2 block text-sm font-medium text-zinc-300">Prepare and hand off live orders.</span></button><button onClick={()=>choose("display")} className="rounded-2xl bg-zinc-100 p-5 text-left font-black">Customer Display<span className="mt-2 block text-sm font-medium">Show ready ticket numbers.</span></button></div><p className="mt-7 text-sm text-zinc-500">Setup is designed for business owners and staff, not developers.</p></section></main>}
export default function App(){const[path,setPath]=useState(window.location.pathname);useEffect(()=>{const update=()=>setPath(window.location.pathname);window.addEventListener("popstate",update);return()=>window.removeEventListener("popstate",update)},[]);if(path==="/register")return <PosRegisterGate/>;if(path==="/kitchen")return <PosKitchen/>;if(path==="/display")return <PosDisplay/>;if(path==="/shifts")return <PosShifts/>;if(path==="/printer")return <PrinterSettings/>;return <DeviceSetup/>}
